# Site settings
title: Good Deed
email: sws-good-deed@googlegroups.com
description:  # this means to ignore newlines until "baseurl:"
  Good Deed is a social platform for sharing the good deeds of the world.
  Join us in sharing the good people can do!
#baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://good-deed-web.netlify.app/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

#future: true  #FOR DEV

# Build settings
markdown: kramdown
